[core] raise `ActionError` if required Action kwargs get `nil` value
replaces `undefined method _ for nil` with new `ActionError`

While validating locally for #12086 and #12095, I happened to have local
games broken by #12073 (they are pinned in prod), and the error was very
unhelpful:

`#<NoMethodError: undefined method `id' for nil:NilClass>"`

Additionally, `broken_action.to_h` caused its own error in the validate
script, as the error was coming from the Action -> hash conversion.

With these changes, the error is much more helpful, making it much easier to
identify the source of the breakage:

`#<Engine::ActionError: Cannot create Engine::Action::LayTile, h_to_args() returned nil :tile from action 745>`