raise ActionError when REQUIRED_ARGS are missing for action creation
While validating locally for #12086 and #12095, I happened to have local games
broken by #12073 (they are pinned in prod), and the error was very unhelpful:

`#<NoMethodError: undefined method `id' for nil:NilClass>"`

Additionally, `broken_action.to_h` caused its own error in the validate script,
as the error was coming from the hash/Action conversion.

With these changes, the error is much more helpful, and the `broken_action` is
populated in the validation output:

```
    "exception": "#<Engine::ActionError: Cannot create Engine::Action::LayTile, h_to_args() returned nil :tile from action 745>",
    "broken_action": {
      "hex": "S13",
      "tile": "50-2",
      "type": "lay_tile",
      "entity": "LSWR",
      "rotation": 2,
      "entity_type": "corporation",
      "id": 745,
      "user": 1046,
      "created_at": 1727531362
    }
```